# Generated by Django 4.1 on 2022-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topping_1",
                    models.CharField(max_length=70, verbose_name="Topping 1"),
                ),
                (
                    "topping_2",
                    models.CharField(max_length=70, verbose_name="Topping 2"),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("1", "small"), ("2", "medium"), ("3", "large")],
                        default="TR",
                        max_length=2,
                        verbose_name="Size",
                    ),
                ),
            ],
        ),
    ]
