# Generated by Django 4.1 on 2022-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_size_alter_pizza_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Size"),
        ),
    ]
